credentials:
  usernames:
    dad:
      name: Dad
      password: $2b$12$YOUR_HASHED_PASSWORD_HERE # will update this later
    mum:
      name: Mum
      password: $2b$12$YOUR_HASHED_PASSWORD_HERE
    son:
      name: Son
      password: $2b$12$YOUR_HASHED_PASSWORD_HERE
cookie:
  expiry_days: 30
  key: random_signature_key
  name: exercise_logger_cookie
